import mongoose from "mongoose";

// A "user" collection must be registered with Mongoose to get access the values (besides _id) from collection generated by Better Auth
// e.g. calling .populate("uploader", "name")) to display the username of a collaborator on the Project page.

const UserSchema = new mongoose.Schema(
  {
    name: String,
    email: String,
  },
  { collection: "user" }, // Better Auth's default collection name
);

export default mongoose.models.User || mongoose.model("User", UserSchema);
